---
title: "PEC2 - INFORME"
output: word_document
---

# Estudio de expresión RNA-seq para dos tipos de infiltración en diferentes tejidos

## Nadia Moltó Lliso 

# Abstract

RNA-seq permite obtener datos de expresión a partir del transcriptoma de las células que se deseen analizar, en este caso, mediante esta técnica, se obtuvieron datos de expresión a partir de diferentes tejidos con dos tipos de infiltración diferentes y un control en el que no hubo infiltración para muestras procedentes de un análisis de tiroides.Mediante el empleo de R a través de Bioconductor se pudieron extraer los resultados del presente análisis.


# Palabras clave

RNA-seq, DESeq2, expresión.

# Objetivos

El objetivo del presente estudio es el de detectar los genes diferencialmente expresados en varios tejidos bajo las diferentes técnicas de infiltración en muestras procedentes de un análisis de tiroides, para ello, partiendo de los resultados de la cuantificación de coincidencias en el alineamiento proporcionados, se empleará R para poder dilucidar aquellos genes que sean estadísticamente significativos en cuanto a expresión de los mismos.

# Materiales y métodos

Los datos facilitados para el presente estudio consistieron en dos archivos CSV que contenían, por un lado el conteo de aquellos genes resultante tras el alineamiento obtenido a partir de los datos de RNA-seq obtenidos e identificados con el nombre de la muestra de la cual se obtuvieron ("counts.csv" del repositorio GitHub) y, por otro lado, los datos de la totalidad de las muestras tomadas, en el que se incluian el identificador de la muestra y otros datos relevantes sobre la procedencia de la misma ("targets.csv" del repositorio GitHub). Entre los datos facilitados en el archivo "targets.csv" se encontraban tres identificadores: 

 - "NIT" : Tejidos sin infiltración. Con 236 muestras.
 - "SFI" : Infiltración focalizada. Con 42 muestras.
 - "ELI" :  Infiltración linfoide extendida. Con 14 muestras.

Por tal de reducir la complejidad y durabilidad del experimento, el número de muestras se redujo a 10 muestras aleatorias para cada tipo de infiltración. Para ello y para el resto del estudio realizado, el programa empleado fue R 3.6.3. descargado a través de su página oficial de libre acceso[1] y se empleó, junto con el mismo, el programama RStudio-1.2.5033, el cual, gracias a su interfaz, facilitó la ejecución e interpretación del código R.

Una vez obtenidas las 10 muestras aleatorias para cada tipo de infiltración (ver ANEXO I - Comandos empleados) se procedió a integrar los datos de ambos archivos facilitados en un mismo archivo, por tal de facilitar su posterior análisis e interpretación según el formato reconocido por el paquete DESeq2 de R que fue el empleado para estudiar los datos facilitados y obtenidos a partir de RNA-seq.
Los pasos a seguir a partir de este punto fueron:

Estos fueron los paquetes necesarios para llevar a cabo el estudio:
```{r}
library("pheatmap")
library("RColorBrewer")
require("dplyr")
library("Biobase")
require("DESeq2")
library("apeglm")
library("pheatmap")
library("genefilter")
require("ggplot2")
library("limma")
```

## 1.Preprocesado de los datos: filtraje y normalización

El primer paso fue crear el dataset según el formato que emplea DESeq2 empleando la función mostrada a continuación, para ello, se indicó que la variable a analizar era "Group", la cual contenia los diferentes tipos de infiltración (Ver anexo I).

colsample <- targets30
dds <- DESeqDataSetFromMatrix(countData = countsample,
                                  colData = targets30,
                                  design = ~ Group)
                                
A continuación se realizó un prefiltrado de los datos, en el cual se eliminaron aquellas filas, es decir, aquellos genes que presentaban un valor en el contaje igual a 0, se mantuvieron aquellos con un valor igual o superior a 1 por tal de no sesgar los resultados, teniendo en cuenta que aquellos genes con un conteo igual a 1 podrían ser significativos.
Se generó una PCA por ver el comportamiento de los datos. El resultado se muestra a continuación y los comandos empleados pueden verse en el Anexo I. 
Para este tipo de análisis gráficos es muy importante la homocedasticidad, la cual consiste en que la varianza de los datos es más o menos uniforme, en este caso y en general como ocurre en los experimentos RNA-seq no hay homocedasticidad en los datos al presentar varianzas muy distintas debido a las diferencias entre conteos [2]. Los genes que presentan un mayor recuento muestran mayores diferencias absolutas entre muestras por lo que en cierto modo enmascaran aquellos con un menor contaje, la varianza está desequilibrada. Por ello, se hizo empleo de la función VST de DESeq2, la cual, estabiliza la varianza de los datos al ponerlos en escala log2, de forma que hace que la variabilidad de los recuentos bajos quede patente. En cierto modo, se normalizan los datos que no estaban normalizados en la matriz de conteo.
Lo que va a permitir la normalización es una mejor visualización de los datos.
Por tal de ver el comportamiento de los datos se representaron mediante un análisis de componentes principales (PCA), debido a que los resultados del  mismo no fueron concluyentes, se realizó un GLM-PCA, que presenta una representación de los datos de forma indiferente a la normalización que puede alterar la representación de los mismos, dándole una mayor significancia a datos que pueden no disponer de la misma [3].


## 2. Identificación de genes diferencialmente expresados

Una vez filtrados los datos, normalizados y representados, se procedió a realizar un análisis de expresión diferencial por tal de identificar aquellos genes que estaban diferencialmente expresados en cada una de las tres comparaciones entre tipos de infiltración.
Para ello, se emplearon los datos sin procesar mediante el empleo de la función DESeq, la cual sigue una serie de pasos para adaptar los datos al análisis:

1. Estimación de los factores de tamaño de muestras.
2. Estimación de la dispersión de los datos.
3. Ajuste binomial negativo GLM y estadístico de Wald.

Con esto se generó un conjunto de datos listos para ser analizados y poder ver las diferencias de expresión.
Puesto que en el presente estudio contenía tres tipos de comparaciones, tal y como se comenta anteriormente, se procedió a la elaboración de 3 conjuntos de resultados todos ellos a partir del paquete DESeq, uno para cada una de las comparaciones entre infiltraciones: ELI-NIT, ELI-SFI, NIT-SFI (ver Anexo I).
A partir de los mismos, se elaboró una tabla de resultados para cada una de las comparaciones, en la cual se mostraron parámetros para cada comparación, entre los cuales se encuntraban:

- baseMean: promedio de los valores de conteo normalizados, dividido por los factores de tamaño de la muestra obtenidos con DESeq.

- log2folgchange: Estimación del tamaño del efecto, cambio de la expresion entre métodos de infiltración de la comparación realizada para esa tabla.

- lfcSE: Incertidumbre asociada a la estimación.

- stat: Resultado de la prueba estadística.

- pvalue: P-value de la prueba estadística

Con la función summary() para cada uno de los resultados se obtuvo de una forma más resumida el conjunto de los parámetros resultantes de la comparación.

En este punto, se vio el número de genes diferencialmente expresados tando a un nivel en aumento como en descenso para cada una de las comparaciones y se representaron en diagramas de barras los p-valores resultantes, de esta forma se pudo verificar que el número de genes diferencialmente expresados se correspondiera con estos gráficos.
La representación de un MAplot paralelamente ayudó a contrastar con la distribución de los genes según el log2 obtenido para cada uno.

## 3. Anotación de los resultados

Tras la obtención de los genes diferencialmente expresados, se procedió a la anotación de los resultados obtenidos en los puntos anteriores.
El paquete empleado para la anotación fue el org.Hs.eg.db del genoma humano.Este paquete contiene diferentes claves disponibles para diferentes bases de datos. Junto con el paquete AnnotationDbi se obtuvieron identificadores de los genes diferencialmente expresados para ENTREZ a partir del ID y el symbol de esta base de datos (ver Anexo I y apartado resultados - Anotación).
Los resultados obtenidos se muestran en el Anexo I a través de un enlace HTML y en los archivos CSV disponibles en el repositorio de GitHub que aparece en el encabezado del presente trabajo.


## 4. Busca de patrones de expresión y agrupación de las muestras (comparación entre las distintas comparaciones).

Por tal de ver si entre las comparaciones realizadas existían genes en comun y por tal de ver el número de genes diferencialmente expresados en cada caso se representó un diagrama de Venn en el que se pudo comprobar el número de genes que aparecían diferencialmente expresados en común entre las tres comparaciones, sin tener en cuenta si los genes estaban sobrerregulados o infrarregulados.
Para ello, se hizo uso del paquete limma.

## 5. Análisis de significación biológica (“Gene Enrichment Analysis”)

Llegados este punto, ya se disponía del listado de genes diferencialmente expresados para cada una de las comparaciones en archivos CSV y se sabía cuántos genes en común diferencialmente expresados tenían cada una de las tres comparaciones.


# Resultados y discusión

## Identificación de genes diferencialmente expresados 

La identificación de genes diferencialmente expresados para cada una de las tres comparaciones realizadas, se obtuvo, según lo mencionado anteriormente, mediante el empleo del paquete DESeq, el cual, según lo mostrado a continuación y para un p valor ajustado del 0,1 permitió obtener los siguientes datos de cada una de las comparaciones realizadas: 


## Anotación de los resultados



# Bibliografía 

[1] https://cran.r-project.org/bin/windows/base/
[2] Anders, S., & Huber, W. (2010). Differential expression analysis for sequence count data. Nature Precedings, 1-1.
[3]Townes, F. W., Hicks, S. C., Aryee, M. J., & Irizarry, R. A. (2019). Feature selection and dimension reduction for single-cell RNA-Seq based on a multinomial model. Genome biology, 20(1), 1-16.


# Anexo I  - Comandos empleados
